### PR TITLE
DT-2117 Set locale to formatter for proper ISO string mapping

### PR DESCRIPTION
**Pull request by MaxRandom**
MTDates has an issue with mapping ISO string to date in some cases.
To fix this I set locale to formatter

### CODE REVIEW

**Comment by goncharik** [comment]
ok

**Comment by zuffko** [comment]
ok

**Comment by demalex** [comment]
What cases do you mean?

**Comment by MaxRandom** [comment]
@demalex  Now we faced with this issue on iOS 8

**Comment by demalex** [comment]
Ok

**Pull request merged**
